/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WelcomeApplet.java
 *
 * Created on 11-Dec-2010, 22:17:08
 */

package user;

import java.applet.AppletContext;
import java.awt.Cursor;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

/**
 *
 * @author pythonee
 */
public class WelcomeApplet extends javax.swing.JApplet {
    final static Logger log = Logger.getLogger("Welcome");

    /** Initializes the applet WelcomeApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        setSize(618,410);
    }


    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createLink = new javax.swing.JLabel();
        loginLink = new javax.swing.JLabel();
        accountLink = new javax.swing.JLabel();
        formNameLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createLink.setForeground(new java.awt.Color(0, 0, 255));
        createLink.setText("Create an Account");
        createLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createLinkMouseExited(evt);
            }
        });
        getContentPane().add(createLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 123, 131, -1));

        loginLink.setForeground(new java.awt.Color(0, 0, 255));
        loginLink.setText("Login in to manage your bank account");
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginLinkMouseExited(evt);
            }
        });
        getContentPane().add(loginLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 185, -1, -1));

        accountLink.setForeground(new java.awt.Color(0, 0, 255));
        accountLink.setText("Open a bank account");
        accountLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountLinkMouseExited(evt);
            }
        });
        getContentPane().add(accountLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 249, -1, -1));

        formNameLabel.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 18));
        formNameLabel.setText("Welcome");
        getContentPane().add(formNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, 87, -1));

        logoLabel.setFont(new java.awt.Font("WenQuanYi Micro Hei", 0, 18));
        logoLabel.setText("E-Banking");
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 28, -1, 18));
    }// </editor-fold>//GEN-END:initComponents

    private void createLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLinkMouseEntered
        
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_createLinkMouseEntered

    private void createLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLinkMouseExited
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_createLinkMouseExited

    private void createLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLinkMouseClicked
        
        try {
            URL url = new URL(getCodeBase().toString()+"register.jsp");
            AppletContext ac =  this.getAppletContext();
            ac.showDocument(url);
            log.info("link jump to register.jsp");
        } catch (MalformedURLException e) {
            log.severe(e.getMessage());
        }
    }//GEN-LAST:event_createLinkMouseClicked

    private void loginLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseEntered
        
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_loginLinkMouseEntered

    private void loginLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseExited
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_loginLinkMouseExited

    private void loginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseClicked
        
        try {
            URL url = new URL(getCodeBase().toString() + "login.jsp");
            AppletContext ac = this.getAppletContext();
            ac.showDocument(url);
            log.info("link jump to login.jsp");
        } catch (MalformedURLException e) {
            log.severe(e.getMessage());
        }
    }//GEN-LAST:event_loginLinkMouseClicked

    private void accountLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLinkMouseClicked
        
        try {
            URL url = new URL(getCodeBase().toString() + "open.jsp");
            AppletContext ac = this.getAppletContext();
            ac.showDocument(url);
            log.info("link jump to open.jsp");
        } catch (MalformedURLException e) {
            log.severe(e.getMessage());
        }
    }//GEN-LAST:event_accountLinkMouseClicked

    private void accountLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLinkMouseEntered
        
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_accountLinkMouseEntered

    private void accountLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountLinkMouseExited
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_accountLinkMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLink;
    private javax.swing.JLabel createLink;
    private javax.swing.JLabel formNameLabel;
    private javax.swing.JLabel loginLink;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables

}
