application: py-note
version: beta
runtime: python27
api_version: 1
threadsafe: true

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (bulkloader.*)|
 (my_transform\.py)|
 (LICENSE\.txt)|
 (README\.txt)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 (dontupload/.*)
 )$

builtins:
#- datastore_admin: on
- deferred: on
- remote_api: on
#- appstats: on

inbound_services:
- warmup
- mail

default_expiration: "1d"

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /(.+[\.-_](\d+\.)+(js|css))
  static_files: static/\1
  upload: static/.+[\.-_](\d+\.)+(js|css)
  expiration: "365d"

- url: /images
  static_dir: static/images

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /ckeditor
  static_dir: static/ckeditor

- url: /syntaxhighlighter
  static_dir: static/syntaxhighlighter

- url: /admin/.*
  script: admin.application
  login: admin

- url: .*
  script: wikipad.application

error_handlers:
  - file: fatal_error.html

  - error_code: over_quota
    file: over_quota.html

  - error_code: timeout
    file: timeout.html
