application: py-demos
version: beta
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (bulkloader.*)|
 (my_transform\.py)|
 (LICENSE\.txt)|
 (README\.txt)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 (dontupload/.*)
 )$

builtins:
- datastore_admin: on
- deferred: on
- remote_api: on
 
handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /csshover3\.htc
  static_files: static/csshover3.htc
  upload: static/csshover3.htc
  mime_type: text/x-component

- url: /image
  static_dir: static/image

- url: /lib
  static_dir: static/lib

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: .*
  script: index.py
